spring.datasource.url=jdbc:postgresql://localhost:5432/hexagonal
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.pool-name=HexagonalHikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

logging.level.io.github.eschoe.hexagonal=DEBUG
logging.level.org.springframework.jdbc=INFO
